# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 15:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('key', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Slot Name')),
            ],
            options={
                'verbose_name_plural': 'Slots',
                'verbose_name': 'Slot',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Team Name')),
                ('flag', models.CharField(db_index=True, max_length=10, verbose_name='Flag')),
            ],
            options={
                'verbose_name_plural': 'Teams',
                'verbose_name': 'Team',
            },
        ),
        migrations.AddField(
            model_name='slot',
            name='chosen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='draw.Team'),
        ),
    ]
