# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='flag',
            field=models.CharField(db_index=True, max_length=10, null=True, verbose_name='Flag'),
        ),
    ]
