# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0002_auto_20160323_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='flag',
            field=models.CharField(blank=True, db_index=True, default='', max_length=10, verbose_name='Flag'),
            preserve_default=False,
        ),
    ]
