# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 04:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0003_auto_20160323_1522'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slot',
            options={'ordering': ['key'], 'verbose_name': 'Slot', 'verbose_name_plural': 'Slots'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['seq', 'id'], 'verbose_name': 'Team', 'verbose_name_plural': 'Teams'},
        ),
        migrations.AddField(
            model_name='team',
            name='seq',
            field=models.IntegerField(default=0, verbose_name='Order Sequence'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='chosen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='draw.Team'),
        ),
    ]
